# Generated by Django 5.1.6 on 2025-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(blank=True, choices=[('morning', 'ช่วงเช้า'), ('afternoon', 'ช่วงบ่าย')], max_length=20, null=True),
        ),
    ]
