# Generated by Django 5.1.6 on 2025-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_schedule_end_time_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
