# Generated by Django 5.1.1 on 2024-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_car_image_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="horsepower",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="detail",
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
