# Generated by Django 5.1.6 on 2025-03-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_carreview_rating_alter_carreview_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contact_owner',
            field=models.BooleanField(default=False, verbose_name='ต้องการให้ติดต่อเจ้าของรถ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(blank=True, choices=[('morning', 'ช่วงเช้า'), ('afternoon', 'ช่วงบ่าย'), ('custom', 'กำหนดเอง')], max_length=20, null=True),
        ),
    ]
