# Generated by Django 5.1.1 on 2024-12-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_car_horsepower_remove_schedule_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="horsepower",
            field=models.IntegerField(default=0, verbose_name="แรงม้า"),
        ),
    ]
