# Generated by Django 5.1.1 on 2024-12-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_car_horsepower"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="time",
            field=models.CharField(
                choices=[("morning", "ช่วงเช้า"), ("afternoon", "ช่วงบ่าย")],
                default=0,
                max_length=10,
            ),
        ),
    ]
