# Generated by Django 5.1.1 on 2024-12-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_car_status_alter_schedule_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, default="default_car.jpg", null=True, upload_to="cars/"
            ),
        ),
    ]
