# Generated by Django 5.1.1 on 2025-01-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_customuser"),
    ]

    operations = []
