# Generated by Django 5.1.1 on 2025-01-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_car_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="myapp.cartype",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[("Approved", "Approved"), ("Pending", "Pending")],
                max_length=20,
            ),
        ),
    ]
