# Generated by Django 5.1.1 on 2025-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_car_is_available_alter_car_car_type_alter_car_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
