# Generated by Django 5.1.1 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_notification_is_confirmed_notification_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
