# Generated by Django 5.1.1 on 2025-02-03 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_schedule_booked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrower_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
