# Generated by Django 5.1.1 on 2025-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_car_owner_alter_car_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="afternoon_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาเหมา ช่วงบ่าย",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="morning_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาเหมา ช่วงเช้า",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="price_per_rai",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาต่อไร่",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="pricing_type",
            field=models.CharField(
                choices=[("flat", "ราคาเหมา"), ("per_rai", "ราคาต่อไร่")],
                default="flat",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="time_per_rai",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="เวลาทำงานต่อไร่ (นาที)"
            ),
        ),
    ]
