# Generated by Django 5.1.1 on 2025-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_car_afternoon_price_car_morning_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="pricing_type",
        ),
        migrations.AddField(
            model_name="car",
            name="afternoon_custom_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาที่กำหนดเอง ช่วงบ่าย",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="morning_custom_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคาที่กำหนดเอง ช่วงเช้า",
            ),
        ),
    ]
